### ISSUE TITLE
Provide "length" of enclosure

### ISSUE THREAD

**Issue by jtgd** [oldlaptop/rsstail#1]
(Given the comment in the readme I'm not sure if it makes sense to request a feature, but here goes)

The enclosure also has a `length` element:
` <enclosure url="https://..." length="834470896" ...`

It would be nice to have the option to output this value.

**Comment by oldlaptop** [comment]
It indeed doesn't make much sense to open issues on this repository, especially because there appears to be a new canonical upstream:

https://github.com/folkertvanheusden/rsstail
